config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #===============================================
  #Home routes
  #===============================================
  root 'home#index'
  get '/standings' => 'home#standings'
  get '/docs' => 'home#docs'

  #===============================================
  #API routes
  #===============================================
  get '/api/stock' => 'api#stock_quote'
  get '/api/stock/list' => 'api#stock_list'
  get '/api/buy' => 'api#buy'
  get '/api/sell' => 'api#sell'
  get '/api/account' => 'api#account'

  #===============================================
  #Broker routes
  #===============================================
  get '/broker' => 'broker#show'

  get '/broker/register' => 'broker#new'
  post '/broker/register' => 'broker#create'

  get '/broker/login' => 'broker#login'
  post '/broker/login' => 'broker#authenticate'

  #===============================================
  #Admin routes
  #===============================================
  get '/admin' => 'admin#show'

  get '/admin/configure' => 'admin#new'
  post '/admin/configure' => 'admin#create'

  get 'admin/login' => 'admin#login_form'
  post 'admin/authenticate' => 'admin#authenticate'

  #===============================================
  #Stock routes
  #===============================================
  #post '/stock/new' => 'stock#create'
  #post '/stock/update' => 'stock#update'
  #post '/stock/delete' => 'stock#destroy'

  # get '/stock/:ticker' => 'stock#show'

  # get '/stock/api/:ticker' => 'stock#query_single'

  #===============================================
  #SideKiq routes
  #===============================================
  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
  post '/api/linux_workshop' => 'api#uotta_hack'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :load_brokers, only: %w(index standings)

  def standings
    sorted_brokers = @brokers.sort { |b1, b2| b2.total_value <=> b1.total_value }
    render json: sorted_brokers.map{ |b| { name: b.name, data: b.historical_portfolio.map.with_index { |x, i| [i, x/100.0] } } }
  end

  def load_brokers
    @brokers = Broker.all
  end
end

app/views/home/_broker_performance.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item active">
    <a class="nav-link" aria-expanded="true" data-toggle="tab" href="#daily">Daily</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#weekly">Weekly</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#monthly">Monthly</a>
  </li>
</ul>
<div id="myTabContent" class="tab-content">
  <div class="tab-pane fade in active" id="daily">
    <%= line_chart standings_path, refresh: 60, xtitle: "Day", ytitle: "Portfolio Value($)", legend: "right" %>
  </div>
  <div class="tab-pane fade" id="weekly">
    <%= line_chart standings_path, refresh: 60, xtitle: "Day", ytitle: "Portfolio Value($)", legend: "right" %>
  </div>
  <div class="tab-pane fade" id="monthly">
    <%= line_chart standings_path, refresh: 60, xtitle: "Day", ytitle: "Portfolio Value($)", legend: "right" %>
  </div>
</div>

app/views/home/_market_performance.html.erb
<div class="row">
  <div class="col-sm-2">
    <h5>Day Change</h5>
  </div>
  <div class="col-sm-2">
    <div class="alert alert-success">
      <h5>+4.89%</h5>
    </div>
  </div>
  <div class="col-sm-2">
    <h5>Gainer</h5>
  </div>
  <div class="col-sm-2">
    <div class="alert alert-success">
      <h5>+11.29%</h5>
    </div>
  </div>
  <div class="col-sm-2">
    <h5>Loser</h5>
  </div>
  <div class="col-sm-2">
    <div class="alert alert-danger">
      <h5>-4.32%</h5>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-2">
    <h5>10 Day Change</h5>
  </div>
  <div class="col-sm-2">
    <div class="alert alert-success">
      <h5>+4.89%</h5>
    </div>
  </div>
  <div class="col-sm-2">
    <h5>Index</h5>
  </div>
  <div class="col-sm-2">
    <div class="alert alert-success">
      <h5>+11.29%</h5>
    </div>
  </div>
  <div class="col-sm-2">
    <h5>Volume</h5>
  </div>
  <div class="col-sm-2">
    <div class="alert alert-danger">
      <h5>-4.32%</h5>
    </div>
  </div>
</div>

app/views/home/docs.html.erb
<% @page_title = "Stock Bots" %>
<div class="container-fluid">
  <div class="jumbotron">
    <h1 class="display-3">StockDocs</h1>
    <p>Automating the next financial crisis</p>
    <p><a class="btn btn-outline-primary btn-lg" href="/">Standings</a></p>
  </div>
  <div class="markdown-wrapper">
    <%= render 'docs' %>
  </div>
</div>

app/views/home/index.html.erb
<% @page_title = "Stock Bots" %>
<div class="container-fluid">
  <div class="jumbotron">
    <h1 class="display-3">StockBots</h1>
    <p>Automating the next financial crisis</p>
    <p><a class="btn btn-outline-primary btn-lg" href="/docs">Docs</a></p>
  </div>
  <h1 align="center">Market Performance</h1>
  <%= render 'market_performance' %>

  <h1 align="center">Broker Performance</h1>
  <%= render 'broker_performance' %>
</div>